/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */

  docs: [
    'index',
    /* Scripts */
    {
      type: 'category',
      label: 'Scripts',
      link: {
        type: 'generated-index',
        title: 'Scripts',
        description: 'คู่มือประกอบการใช้งานสำหรับสินค้า FiveM Scripts ที่ถูกพัฒนาโดย Friendly Fire Studio',
        keywords: ['scripts'],
      },
      collapsed: false,
      items: [
        /* azael_playpass */
        {
          type: 'category',
          label: 'azael_playpass',
          link: {
            type: 'doc',
            id: 'script/azael_playpass/index',
          },
          items: [
            {
              type: 'category',
              label: 'Config',
              items: [
                'script/azael_playpass/config/auth',
                'script/azael_playpass/config/setup',
                'script/azael_playpass/config/core',
                'script/azael_playpass/config/external_api',
                'script/azael_playpass/config/queue',
                'script/azael_playpass/config/profile',
                'script/azael_playpass/config/command',
                'script/azael_playpass/config/nui',
              ],
            },
            {
              type: 'category',
              label: 'Modules',
              items: [
                {
                  type: 'category',
                  label: 'Commands',
                  items: [
                    'script/azael_playpass/modules/commands/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Database',
                  items: [
                    'script/azael_playpass/modules/database/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'External API',
                  items: [
                    'script/azael_playpass/modules/external-api/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Hooks',
                  items: [
                    'script/azael_playpass/modules/hooks/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Logger',
                  items: [
                    'script/azael_playpass/modules/logger/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'NUI',
                  items: [
                    'script/azael_playpass/modules/nui/client',
                  ],
                },
                {
                  type: 'category',
                  label: 'Player',
                  items: [
                    'script/azael_playpass/modules/player/client',
                    'script/azael_playpass/modules/player/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Profile',
                  items: [
                    'script/azael_playpass/modules/profile/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Queue',
                  items: [
                    'script/azael_playpass/modules/queue/server',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Exports',
              items: [
                'script/azael_playpass/exports/client',
                'script/azael_playpass/exports/server',
              ],
            },
            'script/azael_playpass/commands',
            'script/azael_playpass/tutorials',
          ],
        },
        /* azael_dc-serverlogs */
        {
          type: 'category',
          label: 'azael_dc-serverlogs',
          link: {
            type: 'doc',
            id: 'script/azael_dc-serverlogs/index',
          },
          items: [
            {
              type: 'category',
              label: 'Config',
              items: [
                'script/azael_dc-serverlogs/config/auth',
                'script/azael_dc-serverlogs/config/server',
                'script/azael_dc-serverlogs/config/client',
                'script/azael_dc-serverlogs/config/shared',
                {
                  type: 'category',
                  label: 'Events',
                  items: [
                    'script/azael_dc-serverlogs/config/events/custom',
                    'script/azael_dc-serverlogs/config/events/discord',
                  ],
                },
                {
                  type: 'category',
                  label: 'Weapons',
                  items: [
                    'script/azael_dc-serverlogs/config/weapons/fivem',
                    'script/azael_dc-serverlogs/config/weapons/redm',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Public',
              items: [
                'script/azael_dc-serverlogs/public/framework',
                'script/azael_dc-serverlogs/public/hook',
              ],
            },
            {
              type: 'category',
              label: 'Exports',
              items: [
                'script/azael_dc-serverlogs/export/server',
                'script/azael_dc-serverlogs/export/client',
              ],
            },
            'script/azael_dc-serverlogs/tutorial',
            {
              type: 'category',
              label: 'Examples',
              link: {
                type: 'generated-index',
                title: 'Code Examples',
                description: 'ตัวอย่างรหัสที่ใช้เพิ่มไปยังทรัพยากรอื่นๆเพื่อส่งข้อมูลมายัง azael_dc-serverlogs',
                keywords: ['code-examples'],
                slug: 'script/azael_dc-serverlogs/examples',
              },
              items: [
                {
                  type: 'category',
                  label: 'ESX Framework',
                  link: {
                    type: 'generated-index',
                    title: 'ESX Framework',
                    description: 'ตัวอย่างรหัสที่ใช้เพิ่มไปยังทรัพยากร ESX Framework เพื่อส่งข้อมูลมายัง azael_dc-serverlogs',
                    keywords: ['esx-framework'],
                  },
                  items: [
                    'script/azael_dc-serverlogs/example/esx/es_extended',
                    'script/azael_dc-serverlogs/example/esx/esx_society',
                    'script/azael_dc-serverlogs/example/esx/esx_billing',
                    'script/azael_dc-serverlogs/example/esx/esx_policejob',
                    'script/azael_dc-serverlogs/example/esx/esx_ambulancejob',
                    'script/azael_dc-serverlogs/example/esx/esx_mechanicjob',
                    'script/azael_dc-serverlogs/example/esx/esx_vehicleshop',
                    'script/azael_dc-serverlogs/example/esx/esx_boat',
                    'script/azael_dc-serverlogs/example/esx/esx_garage',
                    'script/azael_dc-serverlogs/example/esx/esx_lscustom',
                    'script/azael_dc-serverlogs/example/esx/esx_accessories',
                    'script/azael_dc-serverlogs/example/esx/esx_clotheshop',
                    'script/azael_dc-serverlogs/example/esx/esx_barbershop',
                    'script/azael_dc-serverlogs/example/esx/esx_weaponshop',
                    'script/azael_dc-serverlogs/example/esx/esx_shops',
                    'script/azael_dc-serverlogs/example/esx/esx_banking',
                    'script/azael_dc-serverlogs/example/esx/esx_drugs',
                  ],
                },
                {
                  type: 'category',
                  label: 'Other Scripts',
                  link: {
                    type: 'generated-index',
                    title: 'Other Scripts',
                    description: 'ตัวอย่างรหัสที่ใช้เพิ่มไปยังทรัพยากรอื่นๆ (Other Scripts) เพื่อส่งข้อมูลมายัง azael_dc-serverlogs',
                    keywords: ['other-scripts'],
                  },
                  items: [
                    'script/azael_dc-serverlogs/example/other/ox_inventory',
                    'script/azael_dc-serverlogs/example/other/nc_inventory',
                    'script/azael_dc-serverlogs/example/other/nc_vault',
                    'script/azael_dc-serverlogs/example/other/nc_economy',
                    'script/azael_dc-serverlogs/example/other/nc_booth',
                    'script/azael_dc-serverlogs/example/other/nc_stealjobs',
                    'script/azael_dc-serverlogs/example/other/nc_tradingjobs',
                    'script/azael_dc-serverlogs/example/other/nc_vehiclestorage',
                    'script/azael_dc-serverlogs/example/other/nc_garage',
                    'script/azael_dc-serverlogs/example/other/nc_musicplayers',
                    'script/azael_dc-serverlogs/example/other/nc_baccarat',
                    'script/azael_dc-serverlogs/example/other/nc_itemset',
                    'script/azael_dc-serverlogs/example/other/monster_vault',
                    'script/azael_dc-serverlogs/example/other/new_banking',
                    'script/azael_dc-serverlogs/example/other/esx_inventoryhud',
                    'script/azael_dc-serverlogs/example/other/esx_giveallplayers',
                    'script/azael_dc-serverlogs/example/other/esx_givevehicle',
                    'script/azael_dc-serverlogs/example/other/esx_advancedgarage',
                    'script/azael_dc-serverlogs/example/other/esx_jb_eden_garage2',
                    'script/azael_dc-serverlogs/example/other/esx-qalle-jail',
                    'script/azael_dc-serverlogs/example/other/lls-mechanic',
                    'script/azael_dc-serverlogs/example/other/gcphone',
                    'script/azael_dc-serverlogs/example/other/dpemotes',
                  ],
                },
              ],
            },
          ],
        },
        /* azael_db-health&armor */
        {
          type: 'category',
          label: 'azael_db-health&armor',
          link: {
            type: 'doc',
            id: 'script/azael_db-health&armor/index',
          },
          items: [
            {
              type: 'category',
              label: 'Config',
              items: [
                'script/azael_db-health&armor/config/auth',
                'script/azael_db-health&armor/config/server',
                'script/azael_db-health&armor/config/client',
                'script/azael_db-health&armor/config/shared',
              ],
            },
            {
              type: 'category',
              label: 'Public',
              items: [
                'script/azael_db-health&armor/public/database',
                'script/azael_db-health&armor/public/framework',
              ],
            },
            {
              type: 'category',
              label: 'Exports',
              items: [
                'script/azael_db-health&armor/export/client',
              ],
            },
          ],
        },
        /* azael_ui-diving */
        {
          type: 'category',
          label: 'azael_ui-diving',
          link: {
            type: 'doc',
            id: 'script/azael_ui-diving/index',
          },
          items: [
            {
              type: 'category',
              label: 'Config',
              items: [
                'script/azael_ui-diving/config/auth',
                'script/azael_ui-diving/config/server',
                'script/azael_ui-diving/config/client',
                'script/azael_ui-diving/config/shared',
                'script/azael_ui-diving/config/database',
              ],
            },
            {
              type: 'category',
              label: 'Exports',
              items: [
                'script/azael_ui-diving/export/client',
              ],
            },
          ],
        },
        /* azael_connshield */
        {
          type: 'category',
          label: 'azael_connshield',
          link: {
            type: 'doc',
            id: 'script/azael_connshield/index',
          },
          items: [
            {
              type: 'category',
              label: 'Config',
              items: [
                'script/azael_connshield/config/auth',
                'script/azael_connshield/config/core',
                'script/azael_connshield/config/command',
                'script/azael_connshield/config/permissions',
              ],
            },
            {
              type: 'category',
              label: 'Modules',
              items: [
                {
                  type: 'category',
                  label: 'Commands',
                  items: [
                    'script/azael_connshield/modules/commands/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Hooks',
                  items: [
                    'script/azael_connshield/modules/hooks/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'IP Reputation',
                  items: [
                    'script/azael_connshield/modules/ip-reputation/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Logger',
                  items: [
                    'script/azael_connshield/modules/logger/server',
                  ],
                },
                {
                  type: 'category',
                  label: 'Player',
                  items: [
                    'script/azael_connshield/modules/player/server',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Exports',
              items: [
                'script/azael_connshield/exports/server',
              ],
            },
            'script/azael_connshield/commands',
          ],
        },
        /* azael_active-identifiers */
        {
          type: 'category',
          label: 'azael_active-identifiers',
          link: {
            type: 'doc',
            id: 'script/azael_active-identifiers/index',
          },
          items: [
            {
              type: 'category',
              label: 'Config',
              items: [
                'script/azael_active-identifiers/config/auth',
                'script/azael_active-identifiers/config/server',
                'script/azael_active-identifiers/config/shared',
              ],
            },
          ],
        },
        /* azael_db-guardian */
        {
          type: 'category',
          label: 'azael_db-guardian',
          link: {
            type: 'doc',
            id: 'script/azael_db-guardian/index',
          },
          items: [
            {
              type: 'category',
              label: 'Config',
              items: [
                'script/azael_db-guardian/config/auth',
                'script/azael_db-guardian/config/server',
              ],
            },
            {
              type: 'category',
              label: 'Public',
              items: [
                'script/azael_db-guardian/public/database',
                'script/azael_db-guardian/public/framework',
                'script/azael_db-guardian/public/fileupload',
              ],
            },
            {
              type: 'category',
              label: 'Exports',
              items: [
                'script/azael_db-guardian/export/server',
              ],
            },
            'script/azael_db-guardian/command',
            'script/azael_db-guardian/tutorial',
          ],
        },
      ],
    },
    /* FAQs */
    // {
    //   type: 'category',
    //   label: 'FAQs',
    //   link: {
    //     type: 'generated-index',
    //     title: 'FAQs',
    //     description: 'คำถามที่พบบ่อย (FAQs) เกียวกับวิธีแก้ไขปัญหาทรัพยากรที่ใช้งานบนแพลตฟอร์ม Cfx.re (FiveM, RedM) ที่ถูกพัฒนาโดย Azael Dev',
    //     keywords: ['faqs'],
    //   },
    //   items: [
    //     {
    //       type: 'category',
    //       label: 'Scripts',
    //       collapsed: false,
    //       items: [
    //         'faq/script/azael_playpass',
    //         'faq/script/azael_dc-serverlogs',
    //         'faq/script/azael_db-health&armor',
    //       ],
    //     },
    //   ],
    // },
  ]
};

export default sidebars;
